[package]
name = "led-name-badge"
version = "0.1.0"
authors = ["@cat_in_136"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hidapi = "1.2.1"
